### ISSUE TITLE
run_tests fails due to missing dependencies

### ISSUE THREAD

**Issue by mgiuca** [chromium/caterpillar#51]
Run `run_tests.py js`. Output:

```
/path/to/caterpillar/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
            ^
Error: No provider for "framework:sinon"! (Resolving: framework:sinon)
    at error (/path/to/caterpillar/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get (/path/to/caterpillar/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/path/to/caterpillar/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /path/to/caterpillar/node_modules/karma/lib/server.js:138:20
    at Array.forEach (native)
    at Server._start (/path/to/caterpillar/node_modules/karma/lib/server.js:137:21)
    at invoke (/path/to/caterpillar/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.start (/path/to/caterpillar/node_modules/karma/lib/server.js:102:18)
    at Object.exports.run (/path/to/caterpillar/node_modules/karma/lib/cli.js:243:26)
    at Object.<anonymous> (/path/to/caterpillar/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

Manually run `npm install karma-sinon`. New output:

```
Chrome 50.0.2657 (Linux 0.0.0) runtime getPlatformInfo gets info FAILED
  Died on test #1     at /path/to/caterpillar/tests/js/polyfills/runtime.polyfill.test.js:86:7: platform is not defined
  ReferenceError: platform is not defined
      at Object.<anonymous> (/path/to/caterpillar/tests/js/polyfills/runtime.polyfill.test.js:87:20)
      at runTest (/path/to/caterpillar/node_modules/qunitjs/qunit/qunit.js:905:28)
      at Object.Test.run (/path/to/caterpillar/node_modules/qunitjs/qunit/qunit.js:890:4)
      at /path/to/caterpillar/node_modules/qunitjs/qunit/qunit.js:1032:11
      at process (/path/to/caterpillar/node_modules/qunitjs/qunit/qunit.js:692:24)
      at begin (/path/to/caterpillar/node_modules/qunitjs/qunit/qunit.js:674:2)
      at /path/to/caterpillar/node_modules/qunitjs/qunit/qunit.js:734:4
```

Needs `karma-sinon` and `platform` packages added to package.json.

**Comment by mgiuca** [comment]
CL: https://codereview.chromium.org/1725373005
